server:
  port: 8088
---

app:
  aws:
    sqs:
      name: testsqs

---

cloud:
  aws:
    credentials:
      accessKey: ${AWS_KEY:dummy}
      secretKey: ${AWS_SECRET:dummy}
    region:
      static: ap-southeast-2
    sqs:
      messageQueue: testsqs